In [1]:
import numpy as np
import pandas as pd

## Create an array from a regular Python list or tuple using the array function

In [7]:
list1 = [1,2,3]
a = np.array(list1)
a

array([1, 2, 3])

In [3]:
a.dtype

dtype('int32')

In [4]:
list2 = [4.2,5.1,6.3]
b = np.array([list1,list2])
b

array([[ 1. ,  2. ,  3. ],
       [ 4.2,  5.1,  6.3]])

In [5]:
b.dtype

dtype('float64')

In [6]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [7]:
c.shape

(2, 2)

## Several Function

In [8]:
np.zeros([2,2])

array([[ 0.,  0.],
       [ 0.,  0.]])

In [9]:
np.ones([2,3])

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [10]:
np.empty([2,3]) 

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [11]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [12]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [2]:
np.linspace(0,10,3) # 11 numbers from 0 to 10

array([  0.,   5.,  10.])