In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
# Create a matrix 
arr1 = np.arange(9).reshape((3,3))

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
# Concatenate itself along axis 1
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
# Concatenate itself along axis 0
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
# Lets create two Series with no overlap
ser1 =  Series([0,1,2],index=['T','U','V'])

ser2 = Series([3,4],index=['X','Y'])

# Use concat (default is axis=0)
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [7]:
# Passing along another axis will produce a DataFrame
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [8]:
# We can specify which specific axes to be used
pd.concat([ser1,ser2],axis=1,join_axes=[['U','V','Y']])

0    1
U  1.0  NaN
V  2.0  NaN
Y  NaN  4.0

In [9]:
# Lets say we wanted to add markers.keys to the concatenation result

# WE can do this with a hierarchical index
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [10]:
# Along the axis=1 then these Keys become column headers
pd.concat([ser1,ser2],axis=1,keys=['cat1','cat2'])

cat1  cat2
T   0.0   NaN
U   1.0   NaN
V   2.0   NaN
X   NaN   3.0
Y   NaN   4.0

In [11]:
# Concatenation in DataFrames

dframe1 = DataFrame(np.random.randn(4,3), columns=['X', 'Y', 'Z'])
dframe2 = DataFrame(np.random.randn(3, 3), columns=['Y', 'Q', 'X'])

In [12]:
#Concat on DataFrame
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN -2.112363  1.156217 -0.628623
1       NaN -0.607642 -0.162152 -0.079291
2       NaN  0.149669 -1.761573  1.075003
3       NaN  0.968949  1.548689 -1.220375
0 -0.380694 -0.693885 -0.889816       NaN
1 -2.148809  1.740805  1.332785       NaN
2  0.205022 -0.349013  1.504242       NaN

In [13]:
#Use ignore_index if you dont care about the index info and just awnt to make a complete DataFrame
pd.concat([dframe1,dframe2],ignore_index=True)

Q         X         Y         Z
0       NaN -2.112363  1.156217 -0.628623
1       NaN -0.607642 -0.162152 -0.079291
2       NaN  0.149669 -1.761573  1.075003
3       NaN  0.968949  1.548689 -1.220375
4 -0.380694 -0.693885 -0.889816       NaN
5 -2.148809  1.740805  1.332785       NaN
6  0.205022 -0.349013  1.504242       NaN