In [11]:
import numpy as np
a = np.array([[0,   0, 0, 1/3, 0,   0], 
              [1/3, 0, 0,   0, 1/2, 0],
              [0,   1, 0, 1/3, 1/2, 0],
              [1/3, 0, 0,   0, 0,   1],
              [0,   0, 1, 1/3, 0,   0],
              [1/3, 0, 0,   0, 0,   0]])
b = np.array([1/6, 1/6, 1/6, 1/6, 1/6, 1/6])
w = b

# 简化模型
def work(a, w):
    for i in range(100):
        w = np.dot(a, w)
        print(w)

#work(a, w)
#print('-'*30)

#随机模型
def random_work(a, w, n):
    d = 0.85
    for i in range(100):
        w = (1-d)/n + d*np.dot(a, w)
        print(w)

random_work(a, w, 6)

------------------------------
[0.07222222 0.14305556 0.28472222 0.21388889 0.21388889 0.07222222]
[0.08560185 0.13636574 0.29810185 0.10685185 0.32761574 0.04546296]
[0.05527469 0.18849055 0.31042226 0.08789738 0.30866127 0.04925386]
[0.04990426 0.1718422  0.34130226 0.08252694 0.31376318 0.04066116]
[0.04838263 0.17248889 0.32779785 0.07370153 0.33848955 0.03913954]
[0.0458821  0.18256647 0.33635572 0.07197702 0.32451028 0.03870841]
[0.04539349 0.1759168  0.33849186 0.07090208 0.33129585 0.03799993]
[0.04508892 0.17866222 0.33541893 0.07016143 0.332807   0.03786149]
[0.04487907 0.17921817 0.33818494 0.06995746 0.32998517 0.03777519]
[0.04482128 0.17795943 0.33740042 0.06982465 0.33227848 0.03771574]
[0.04478365 0.17891772 0.33726752 0.06975774 0.33157401 0.03769936]
[0.04476469 0.17860766 0.33776371 0.06973316 0.33144209 0.0376887 ]
[0.04475773 0.17854622 0.33743712 0.06971873 0.33185688 0.03768333]
[0.04475364 0.17872053 0.3375571  0.06971219 0.33157519 0.03768136]
[0.04475179 0.178